routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\MedicalRecordController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::redirect('/', '/patients');
    Route::name('patients.')->prefix('patients')->group(function () {
        Route::get('/', [PatientController::class, 'index'])->name('index');
        Route::middleware(['check_role:admin,staff'])->group(function (){
            Route::get('/create', [PatientController::class, 'create'])->name('create');
            Route::post('/store', [PatientController::class, 'store'])->name('store');
            Route::get('/{id}/edit', [PatientController::class, 'edit'])->name('edit');
            Route::patch('/{id}', [PatientController::class, 'update'])->name('update');
        });

        Route::middleware(['check_role:doctor,admin'])->group(function (){
            Route::get('/{id}/medical-record/show', [MedicalRecordController::class, 'show'])->name('medical-record.show');
            Route::get('/{id}/medical-record/create', [MedicalRecordController::class, 'create'])->name('medical-record.create');
            Route::post('/{id}/medical-record/store', [MedicalRecordController::class, 'store'])->name('medical-record.store');
            Route::get('/{id}/medical-record/{idMedical}/edit', [MedicalRecordController::class, 'edit'])->name('medical-record.edit');
            Route::patch('/{id}/medical-record/update/{idMedical}', [MedicalRecordController::class, 'update'])->name('medical-record.update');
        });

    });

    Route::name('doctors.')->prefix('doctors')->middleware(['check_role:admin'])->group(function (){
        Route::get('/', [DoctorController::class, 'index'])->name('index');
        Route::get('/create', [DoctorController::class, 'create'])->name('create');
        Route::post('/store', [DoctorController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [DoctorController::class, 'edit'])->name('edit');
        Route::patch('/{id}', [DoctorController::class, 'update'])->name('update');
        Route::post('/add-account', [DoctorController::class, 'addAccount'])->name('add-account');
    });

    Route::name('staffs.')->prefix('staffs')->middleware(['check_role:admin,staff'])->group(function (){
        Route::get('/', [StaffController::class, 'index'])->name('index');
        Route::get('/create', [StaffController::class, 'create'])->name('create');
        Route::post('/store', [StaffController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [StaffController::class, 'edit'])->name('edit');
        Route::patch('/{id}', [StaffController::class, 'update'])->name('update');
    });

    Route::name('users.')->prefix('users')->middleware(['check_role:admin'])->group(function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{id}/edit', [UserController::class, 'edit'])->name('edit');
        Route::patch('/update/{id}', [UserController::class, 'update'])->name('update');
    });
});


Route::get('/login', [LoginController::class, 'getLogin'])->name('login');
Route::post('/login', [LoginController::class, 'postLogin'])->name('login');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

app/Models/Doctor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    use HasFactory;

    protected $table = 'doctors';
    protected $fillable= [
        'name',
        'date_of_birth',
        'gender',
        'phone',
        'address',
        'department',
        'user_id'
    ];
    protected $dates = ['date_of_birth', 'created_at', 'updated_at'];

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%'.$name.'%') : null;
    }

    public function scopeWithDepartment($query, $department)
    {
        return $department ? $query->orWhere('department', 'like', '%'.$department.'%'): null;
    }

    public function scopeWithPhone($query, $phone)
    {
        return $phone ? $query->orWhere('phone', 'like', '%'.$phone.'%'): null;
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Doctor\AddAccountRequest;
use App\Http\Requests\Doctor\DoctorCreateRequest;
use App\Http\Requests\Doctor\DoctorUpdateRequest;
use App\Services\DoctorService;
use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class DoctorController extends Controller
{
    /** @var $doctorService */
    protected $doctorService;

    /** @var $userService */
    protected $userService;

    public function __construct(DoctorService $doctorService, UserService $userService)
    {
        $this->doctorService = $doctorService;
        $this->userService = $userService;
    }

    /**
     * @return \Illuminate\Contracts\View\View
     */
    public function index(Request $request)
    {
        $doctors = $this->doctorService->search($request);
        return view('doctors.index', compact('doctors'));
    }

    /**
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('doctors.create');
    }

    public function store(DoctorCreateRequest $request)
    {
        try {
            $this->doctorService->store($request);
            return redirect()->route('doctors.index')->with('message-success', 'Thêm mới thông tin bác sĩ thành công!');
        } catch (\Exception $e) {
            return redirect()->route('doctors.index')->with('message-failed', 'Thêm mới thông tin bác sĩ thất bại!');
        }
    }

    public function edit($id)
    {
        $doctor = $this->doctorService->find($id);
        return view('doctors.edit', compact('doctor'));
    }

    public function update(DoctorUpdateRequest $request, $id)
    {
        try {
            $this->doctorService->update($request, $id);
            return redirect()->route('doctors.index')->with('message-success',
                'Chỉnh sửa thông tin bác sĩ thành công!');
        } catch (\Exception $e) {
            return redirect()->route('doctors.index')->with('message-failed', 'Chỉnh sửa thông tin bác sĩ thất bại!');
        }
    }

    public function addAccount(AddAccountRequest $request)
    {
        try {
            $this->userService->store($request);
            return response()->json(['message' => 'Thêm tài khoản thành công!', 'status' => Response::HTTP_OK],
                Response::HTTP_OK);
        } catch (\Exception $e) {
            return response()->json([
                'message' => 'Thêm tài khoản thất bại!',
                'status' => Response::HTTP_INTERNAL_SERVER_ERROR
            ], Response::HTTP_OK);
        }
    }
}

resources/views/doctors/create.blade.php
@extends('layouts.app', ['title' => 'Thêm thông tin bác sĩ'])
@section('content')
    <form action="{{ route('doctors.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="name">Họ và tên <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Họ và tên..." value="{{ old('name', request()->name) }}">
                    @error('name')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="date-of-birth">Ngày sinh <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="date_of_birth" id="date-of-birth" placeholder="dd/mm/YYYY" value="{{ old('date_of_birth', request()->date_of_birth) }}">
                    @error('date_of_birth')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="phone">Số điện thoại <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Số điện thoại..." value="{{ old('phone', request()->phone) }}">
                    @error('phone')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="address">Địa chỉ <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="address" id="address" placeholder="Địa chỉ..." value="{{ old('address', request()->address) }}">
                    @error('address')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="department">Khoa <span class="text-danger">*</span></label>
                    <select name="department" id="department" class="form-control">
                        <option value="" disabled selected>---Chọn---</option>
                        @foreach(config('constants.department') as $key => $value)
                            <option value="{{ $key }}" {{ old('department', request()->department) == $key ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('department')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="gender">Giới tính <span class="text-danger">*</span></label>
                    <select name="gender" id="gender" class="form-control">
                        @foreach(config('constants.gender') as $key => $value)
                            <option value="{{ $key }}" {{ old('gender', request()->gender) == $key ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('gender')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="group-btn text-center">
            <a href="{{ route('doctors.index') }}" class="btn btn-danger">
                Quay lại
            </a>
            <button class="btn btn-primary" type="submit">Thêm</button>
        </div>
    </form>
@endsection

@push('js')
@endpush

resources/views/doctors/edit.blade.php
@extends('layouts.app', ['title' => 'Chỉnh sửa thông tin bác sĩ'])
@section('content')
    <form action="{{ route('doctors.update', $doctor->id) }}" method="POST">
        @csrf
        @method('PATCH')
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="name">Họ và tên <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Họ và tên..." value="{{ $doctor->name }}">
                    @error('name')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="date-of-birth">Ngày sinh <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="date_of_birth" id="date-of-birth" value="{{ $doctor->date_of_birth->format('d/m/Y') }}" placeholder="dd/mm/YYYY">
                    @error('date_of_birth')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="phone">Số điện thoại <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Số điện thoại..." value="{{ $doctor->phone }}">
                    @error('phone')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="address">Địa chỉ <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="address" id="address" placeholder="Địa chỉ..." value="{{ $doctor->address }}">
                    @error('address')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="department">Khoa <span class="text-danger">*</span></label>
                    <select name="department" id="department" class="form-control">
                        <option value="" disabled selected>---Chọn---</option>
                        @foreach(config('constants.department') as $key => $value)
                            <option value="{{ $key }}" {{ $doctor->department == $key ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('department')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="gender">Giới tính <span class="text-danger">*</span></label>
                    <select name="gender" id="gender" class="form-control">
                        @foreach(config('constants.gender') as $key => $value)
                            <option value="{{ $key }}"  {{ $doctor->gender == $key ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('gender')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="group-btn text-center">
            <a href="{{ route('doctors.index') }}" class="btn btn-danger">
                Quay lại
            </a>
            <button class="btn btn-primary" type="submit">Chỉnh sửa</button>
        </div>
    </form>
@endsection

@push('js')
@endpush

resources/views/doctors/index.blade.php
@extends('layouts.app', ['title' => 'Bác sĩ'])
@section('content')
    @include('messages.message')
    <div class="d-flex justify-content-between">
        <div class="box-search ">
            <form method="GET" action="{{ route('doctors.index') }}" id="form-search">
                <div class="btn-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm..." name="keyword" value="{{ old('keyword', request()->keyword) }}">
                    <button class="btn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="btn-add-patients">
            <a href="{{ route('doctors.create') }}" class="btn btn-primary">
                <i class="fas fa-plus-circle"></i>
                Thêm Bác sĩ
            </a>
        </div>
    </div>
    <table class="table mt-4">
        <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">Họ và tên</th>
            <th scope="col">Ngày sinh</th>
            <th scope="col">Giới tính</th>
            <th scope="col">Số điện thoại</th>
            <th scope="col">Khoa</th>
            <th scope="col">Hành động</th>
        </tr>
        </thead>
        <tbody>
        @if(count($doctors) > 0)
            <?php $gender = config('constants.gender') ?>
            <?php $department = config('constants.department')?>
            @foreach($doctors as $doctor)
                <tr>
                    <td>{{ $loop->iteration + $doctors->firstItem() - 1 }}</td>
                    <td >{{ $doctor->name }}</td>
                    <td>{{ $doctor->date_of_birth->format('d/m/Y') }}</td>
                    <td>{{ $gender[$doctor->gender] }}</td>
                    <td >{{ $doctor->phone}}</td>
                    <td >{{$department[$doctor->department]}}</td>
                    <td style="width: 150px">
                        <div class="btn-group">
                            <a href="{{ route('doctors.edit', $doctor->id) }}" class="btn btn-sm btn-warning" title="Chỉnh sửa">
                                <i class="fas fa-pen"></i>
                            </a>
                            @if(is_null($doctor->user))
                                <button type="button" class="btn btn-sm btn-success btn-add-account" title="Thêm tài khoản"
                                        data-toggle="modal" data-target="#add-account" data-name="{{ $doctor->name }}" data-id="{{ $doctor->id }}">
                                    <i class="fas fa-user"></i>
                                </button>
                            @else
                                <button type="button" class="btn btn-sm btn-dark btn-add-account" title="Bác sĩ đã có tài khoản" disabled>
                                    <i class="fas fa-user"></i>
                                </button>
                            @endif
                        </div>
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="7" class="text-center text-danger">Không tìm thấy dữ liệu</td>
            </tr>
        @endif
        </tbody>
    </table>
    <div class="box-pagination">
        {{ $doctors->onEachSide(1)->appends(request()->only('keyword'))->links() }}
    </div>
    @include('doctors.modal-add-account')
@endsection
@push('js')
    <script src="{{ asset('js/doctor.js') }}" type="module"></script>
@endpush

resources/views/doctors/modal-add-account.blade.php
<div class="modal fade" id="add-account" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm tài khoản</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="form-add-account" action="{{ route('doctors.add-account') }}">
                    <div class="form-group input-group-sm">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" placeholder="Email..." name="email">
                        <small id="error-email" class="form-text text-danger"></small>
                    </div>
                    <div class="form-group input-group-sm">
                        <label for="password">Mật khẩu</label>
                        <input type="password" class="form-control" id="password" placeholder="Mật khẩu..." name="password">
                        <small id="error-password" class="form-text text-danger"></small>
                    </div>
                    <input type="hidden" name="name" id="input-hidden-name">
                    <input type="hidden" name="role" value="2">
                    <input type="hidden" name="id" id="input-hidden-id">
                    <div class="btn-group-form text-right">
                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary btn-sm">Thêm</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>