routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\MedicalRecordController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::redirect('/', '/patients');
    Route::name('patients.')->prefix('patients')->group(function () {
        Route::get('/', [PatientController::class, 'index'])->name('index');
        Route::middleware(['check_role:admin,staff'])->group(function (){
            Route::get('/create', [PatientController::class, 'create'])->name('create');
            Route::post('/store', [PatientController::class, 'store'])->name('store');
            Route::get('/{id}/edit', [PatientController::class, 'edit'])->name('edit');
            Route::patch('/{id}', [PatientController::class, 'update'])->name('update');
        });

        Route::middleware(['check_role:doctor,admin'])->group(function (){
            Route::get('/{id}/medical-record/show', [MedicalRecordController::class, 'show'])->name('medical-record.show');
            Route::get('/{id}/medical-record/create', [MedicalRecordController::class, 'create'])->name('medical-record.create');
            Route::post('/{id}/medical-record/store', [MedicalRecordController::class, 'store'])->name('medical-record.store');
            Route::get('/{id}/medical-record/{idMedical}/edit', [MedicalRecordController::class, 'edit'])->name('medical-record.edit');
            Route::patch('/{id}/medical-record/update/{idMedical}', [MedicalRecordController::class, 'update'])->name('medical-record.update');
        });

    });

    Route::name('doctors.')->prefix('doctors')->middleware(['check_role:admin'])->group(function (){
        Route::get('/', [DoctorController::class, 'index'])->name('index');
        Route::get('/create', [DoctorController::class, 'create'])->name('create');
        Route::post('/store', [DoctorController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [DoctorController::class, 'edit'])->name('edit');
        Route::patch('/{id}', [DoctorController::class, 'update'])->name('update');
        Route::post('/add-account', [DoctorController::class, 'addAccount'])->name('add-account');
    });

    Route::name('staffs.')->prefix('staffs')->middleware(['check_role:admin,staff'])->group(function (){
        Route::get('/', [StaffController::class, 'index'])->name('index');
        Route::get('/create', [StaffController::class, 'create'])->name('create');
        Route::post('/store', [StaffController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [StaffController::class, 'edit'])->name('edit');
        Route::patch('/{id}', [StaffController::class, 'update'])->name('update');
    });

    Route::name('users.')->prefix('users')->middleware(['check_role:admin'])->group(function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{id}/edit', [UserController::class, 'edit'])->name('edit');
        Route::patch('/update/{id}', [UserController::class, 'update'])->name('update');
    });
});


Route::get('/login', [LoginController::class, 'getLogin'])->name('login');
Route::post('/login', [LoginController::class, 'postLogin'])->name('login');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Patient extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'patients';

    protected $fillable = [
        'name' ,
        'date_of_birth',
        'insurance_code',
        'gender',
        'avatar' ,
        'city' ,
        'district' ,
        'commune',
        'apartment_number',
        'phone'
    ];

    protected $dates = ['date_of_birth', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function medicalRecords() : HasMany
    {
        return $this->hasMany(MedicalRecord::class, 'patient_id', 'id');
    }

    /**
     * @param $query
     * @param $name
     * @return null
     */
    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%'.$name.'%') : null;
    }

    /**
     * @param $query
     * @param $insurance
     * @return null
     */
    public function scopeWithInsurance($query, $insurance)
    {
        return $insurance ? $query->orWhere('insurance_code', 'like', '%'.$insurance.'%') : null;
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Patient\PatientCreateRequest;
use App\Http\Requests\Patient\PatientUpdateRequest;
use App\Services\PatientService;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    /**@var $patientService */
    protected $patientService;

    public function __construct(PatientService $patientService)
    {
        $this->patientService = $patientService;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\View
     */
    public function index(Request $request)
    {
        $patients = $this->patientService->search($request);
        return view('patients.index', compact('patients'));
    }

    /**
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('patients.create');
    }

    /**
     * @param PatientCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PatientCreateRequest $request)
    {
        try {
            $this->patientService->store($request);
            return redirect()->route('patients.index')->with('message-success', 'Thêm mới bệnh nhân thành công!');
        }catch (\Exception $e) {
            return redirect()->route('patients.index')->with('message-failed', 'Thêm mới bệnh nhân thất bại!');
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $patient = $this->patientService->find($id);
        return view('patients.edit', compact('patient'));
    }

    /**
     * @param $id
     * @param PatientUpdateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, PatientUpdateRequest $request)
    {
        try {
            $this->patientService->update($id, $request);
            return redirect()->route('patients.index')->with('message-success', 'Chỉnh sửa thông tin bệnh nhân thành công!');
        }catch (\Exception $e) {
            return redirect()->route('patients.index')->with('message-failed', 'Chỉnh sửa thông tin bệnh nhân thất bại!');
        }
    }
}

resources/views/patients/create.blade.php
@extends('layouts.app', ['title'=>'Thêm bệnh nhân'])
@section('content')
    <form action="{{ route('patients.store') }}" id="form-create-patient" enctype="multipart/form-data" method="POST">
        @csrf
        <div class="info-private row pr-lg-5 pl-lg-5">
            <div class="avatar col-2">
                <div class="form-group">
                    <label>Ảnh</label>
                    <div class="thumbnail-product">
                        <div class="box-thumbnail">
                            <img src="{{asset('images/uploads/avatar-default.jpg')}}" alt="" width="100%" height="100%"
                                 id="thumbnail">
                        </div>
                        @error('avatar')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                        <div class="btn btn-sm btn-success btn-add-thumbnail">
                            Chọn ảnh
                            <input type="file" id="file-thumbnail" name="avatar">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-10">
                <div class="form-group">
                    <label for="name">Họ và tên <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Họ và tên..."
                           value="{{ old('name', request()->name) }}">
                    @error('name')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="date-of-birth">Ngày sinh <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="date_of_birth" id="date-of-birth"
                           placeholder="dd/mm/yyyy" autocomplete="off"
                           value="{{ old('date_of_birth', request()->date_of_birth) }}">
                    @error('date_of_birth')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="phone">Số điện thoại <span class="text-danger">*</span></label>
                    <input name="phone" id="phone" class="form-control" placeholder="Số điện thoại..."
                           value="{{ old('phone', request()->phone) }}">
                    @error('phone')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <label for="city">Thành phố <span class="text-danger">*</span></label>
                    <input name="city" id="city" class="form-control" placeholder="Thành phố..."
                           value="{{ old('city', request()->city) }}">
                    @error('city')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="district">Huyện <span class="text-danger">*</span></label>
                    <input type="text" name="district" id="district" class="form-control" placeholder="Huyện..."
                           value="{{ old('district', request()->district) }}">
                    @error('district')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="commune">Xã <span class="text-danger">*</span></label>
                    <input type="text" name="commune" id="commune" class="form-control" placeholder="Xã..."
                           value="{{ old('commune', request()->commune) }}">
                    @error('commune')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="insurance">Mã bảo hiểm</label>
                    <input type="text" class="form-control" id="insurance" name="insurance_code"
                           placeholder="Mã bảo hiểm..." value="{{ old('insurance_code', request()->insurance_code) }}">
                    @error('insurance_code')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="address">Số nhà <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="address" name="apartment_number"
                           placeholder="Số nhà..." value="{{ old('apartment_number', request()->apartment_number) }}">
                    @error('apartment_number')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="date-of-birth">Giới tính <span class="text-danger">*</span></label>
                    <div class="d-flex align-items-center">
                        <div class="radio d-flex align-items-center">
                            <input id="sex-female" type="radio" name="gender" value="1" checked/>
                            <span style="margin-left: 6px">Nam</span>
                        </div>
                        <div class="radio d-flex align-items-center">
                            <input id="sex-female" type="radio" name="gender" value="2"/>
                            <span style="margin-left: 6px">Nữ</span>
                        </div>
                    </div>
                    @error('gender')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="group-btn text-center">
            <a href="{{ route('patients.index') }}" class="btn btn-danger">
                Quay lại
            </a>
            <button class="btn btn-primary" type="submit">Thêm</button>
        </div>
    </form>
    <div style="height: 200px"></div>
@endsection

resources/views/patients/edit.blade.php
@extends('layouts.app', ['title'=>'Chỉnh sửa bệnh nhân'])
@section('content')
    <form action="{{ route('patients.update', $patient->id) }}" id="form-create-patient" enctype="multipart/form-data" method="POST">
        @csrf
        @method('PATCH')
        <div class="info-private row pr-lg-5 pl-lg-5">
            <div class="avatar col-2">
                <div class="form-group">
                    <label>Ảnh</label>
                    <div class="thumbnail-product">
                        <div class="box-thumbnail">
                            <img src="{{asset('images/uploads/'.$patient->avatar)}}" alt="" width="100%" height="100%" id="thumbnail">
                        </div>
                        @error('avatar')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                        <div class="btn btn-sm btn-success btn-add-thumbnail">
                            Chọn ảnh
                            <input type="file" id="file-thumbnail" name="avatar">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-10">
                <div class="form-group">
                    <label for="name">Họ và tên <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Họ và tên..." value="{{ $patient->name }}">
                    @error('name')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="date-of-birth">Ngày sinh <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="date_of_birth" id="date-of-birth" placeholder="dd-mm-yyyy" value="{{ $patient->date_of_birth->format('d/m/Y') }}">
                    @error('date_of_birth')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="phone">Số điện thoại <span class="text-danger">*</span></label>
                    <input name="phone" id="phone" class="form-control" placeholder="Số điện thoại..." value="{{ $patient->phone }}">
                    @error('phone')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>

            </div>
            <div class="col-12">
                <div class="form-group">
                    <label for="city">Thành phố <span class="text-danger">*</span></label>
                    <input name="city" id="city" class="form-control" placeholder="Thành phố..." value="{{ $patient->city }}">
                    @error('city')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="district">Huyện <span class="text-danger">*</span></label>
                    <input type="text" name="district" id="district" class="form-control" placeholder="Huyện..." value="{{ $patient->district }}">
                    @error('district')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="commune">Xã <span class="text-danger">*</span></label>
                    <input type="text" name="commune" id="commune" class="form-control" placeholder="Xã..." value="{{ $patient->commune }}">
                    @error('commune')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="insurance">Mã bảo hiểm</label>
                    <input type="text" class="form-control" id="insurance" name="insurance_code" placeholder="Mã bảo hiểm..." value="{{ $patient->insurance_code}}">
                    @error('insurance_code')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="address">Số nhà <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="address" name="apartment_number" placeholder="Số nhà..." value="{{ $patient->apartment_number }}">
                    @error('apartment_number')
                    <small class="form-text text-danger" >{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="date-of-birth">Giới tính <span class="text-danger">*</span></label>
                    <div class="d-flex align-items-center">
                        <div class="radio d-flex align-items-center">
                            <input id="sex-female" type="radio" name="gender" value="1" {{ $patient->gender == 1 ? 'checked': ''  }}/>
                            <span style="margin-left: 6px">Nam</span>
                        </div>
                        <div class="radio d-flex align-items-center">
                            <input id="sex-female" type="radio" name="gender" value="2" {{ $patient->gender == 2 ? 'checked': ''  }}/>
                            <span style="margin-left: 6px">Nữ</span>
                        </div>
                    </div>
                    @error('gender')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
        </div>
        <div class="group-btn text-center">
            <a href="{{ route('patients.index') }}" class="btn btn-danger">
                Quay lại
            </a>
            <button class="btn btn-primary" type="submit">Chỉnh sửa</button>
        </div>
    </form>
    <div style="height: 200px"></div>
@endsection

resources/views/patients/index.blade.php
@extends('layouts.app', ['title'=>'Bệnh nhân'])
@section('content')
    @include('messages.message')
    <div class="d-flex justify-content-between">
        <div class="box-search ">
            <form method="GET" action="{{ route('patients.index') }}" id="form-search">
                <div class="btn-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm..." name="keyword" value="{{ old('keyword', request()->keyword) }}">
                    <button class="btn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="btn-add-patients">
            <a href="{{ route('patients.create') }}" class="btn btn-primary">
                <i class="fas fa-plus-circle"></i>
                Thêm Bệnh nhân
            </a>
        </div>
    </div>
    <table class="table mt-4">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Họ và tên</th>
                <th scope="col">Ngày sinh</th>
                <th scope="col">Giới tính</th>
                <th scope="col">Mã bảo hiểm</th>
                <th scope="col">Hành động</th>
            </tr>
        </thead>
        <tbody>
            @if(count($patients) > 0)
                <?php $gender = config('constants.gender') ?>
                @foreach($patients as $patient)
                    <tr>
                        <td>{{ $loop->iteration + $patients->firstItem() - 1 }}</td>
                        <td style="width: 200px">{{ $patient->name }}</td>
                        <td>{{ $patient->date_of_birth->format('d/m/Y') }}</td>
                        <td>{{ $gender[$patient->gender] }}</td>
                        <td style="width: 300px" class="{{ is_null($patient->insurance_code) ? 'text-danger': '' }}">{{ $patient->insurance_code ?? 'N/a' }}</td>
                        <td style="width: 150px">
                            <div class="btn-group">
                                <a href="{{ route('patients.edit', $patient->id) }}" class="btn btn-sm btn-warning" title="Chỉnh sửa">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{{ route('patients.medical-record.create', $patient->id) }}" class="btn btn-sm btn-success" title="Thêm bệnh án">
                                    <i class="fas fa-file-alt"></i>
                                </a>
                                <a href="{{ route('patients.medical-record.show', $patient->id) }}" class="btn btn-sm btn-primary text-white" title="Xem bệnh án">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                   <td colspan="6" class="text-center text-danger">Không tìm thấy dữ liệu</td>
                </tr>
            @endif
        </tbody>
    </table>
    <div class="box-pagination">
        {{ $patients->onEachSide(1)->appends(request()->only('keyword'))->links() }}
    </div>
@endsection