routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\MedicalRecordController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::redirect('/', '/patients');
    Route::name('patients.')->prefix('patients')->group(function () {
        Route::get('/', [PatientController::class, 'index'])->name('index');
        Route::middleware(['check_role:admin,staff'])->group(function (){
            Route::get('/create', [PatientController::class, 'create'])->name('create');
            Route::post('/store', [PatientController::class, 'store'])->name('store');
            Route::get('/{id}/edit', [PatientController::class, 'edit'])->name('edit');
            Route::patch('/{id}', [PatientController::class, 'update'])->name('update');
        });

        Route::middleware(['check_role:doctor,admin'])->group(function (){
            Route::get('/{id}/medical-record/show', [MedicalRecordController::class, 'show'])->name('medical-record.show');
            Route::get('/{id}/medical-record/create', [MedicalRecordController::class, 'create'])->name('medical-record.create');
            Route::post('/{id}/medical-record/store', [MedicalRecordController::class, 'store'])->name('medical-record.store');
            Route::get('/{id}/medical-record/{idMedical}/edit', [MedicalRecordController::class, 'edit'])->name('medical-record.edit');
            Route::patch('/{id}/medical-record/update/{idMedical}', [MedicalRecordController::class, 'update'])->name('medical-record.update');
        });

    });

    Route::name('doctors.')->prefix('doctors')->middleware(['check_role:admin'])->group(function (){
        Route::get('/', [DoctorController::class, 'index'])->name('index');
        Route::get('/create', [DoctorController::class, 'create'])->name('create');
        Route::post('/store', [DoctorController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [DoctorController::class, 'edit'])->name('edit');
        Route::patch('/{id}', [DoctorController::class, 'update'])->name('update');
        Route::post('/add-account', [DoctorController::class, 'addAccount'])->name('add-account');
    });

    Route::name('staffs.')->prefix('staffs')->middleware(['check_role:admin,staff'])->group(function (){
        Route::get('/', [StaffController::class, 'index'])->name('index');
        Route::get('/create', [StaffController::class, 'create'])->name('create');
        Route::post('/store', [StaffController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [StaffController::class, 'edit'])->name('edit');
        Route::patch('/{id}', [StaffController::class, 'update'])->name('update');
    });

    Route::name('users.')->prefix('users')->middleware(['check_role:admin'])->group(function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{id}/edit', [UserController::class, 'edit'])->name('edit');
        Route::patch('/update/{id}', [UserController::class, 'update'])->name('update');
    });
});


Route::get('/login', [LoginController::class, 'getLogin'])->name('login');
Route::post('/login', [LoginController::class, 'postLogin'])->name('login');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

app/Models/MedicalRecord.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MedicalRecord extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table='medical_records';

    protected $fillable = [
        'patient_id',
        'check_in',
        'check_out',
        'where_check_in',
        'total_day',
        'diagnose',
        'pathology',
        'autopsy',
        'time_to_corpse',
        'time_to_examination',
        'time_die',
        'reason_die',
        'name_doctor',
        'result',
        'medical_record_code'
    ];
    protected $dates = ['check_in', 'check_out', 'time_to_corpse', 'time_to_examination', 'time_die'];

    public function doctor()
    {
        return $this->belongsTo(Doctor::class);
    }
}

app/Http/Controllers/MedicalRecordController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MedicalRecord\MedicalRecordCreateRequest;
use App\Http\Requests\MedicalRecord\MedicalRecordUpdateRequest;
use App\Services\MedicalRecordService;
use App\Services\PatientService;
use Illuminate\Http\Request;

class MedicalRecordController extends Controller
{

    /**@var $patientService */
    protected $patientService;

    /** @var $medicalService */
    protected $medicalRecordService;

    public function __construct(PatientService $patientService, MedicalRecordService $medicalRecordService)
    {
        $this->patientService = $patientService;
        $this->medicalRecordService = $medicalRecordService;
    }

    /**
     * @return \Illuminate\Contracts\View\View
     */
    public function create($idPatient)
    {
        $patient = $this->patientService->find($idPatient);
        return view('medical-records.create', compact('patient'));
    }


    /**
     * @param $idPatient
     * @param MedicalRecordCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store($idPatient, MedicalRecordCreateRequest $request)
    {
        try {
            $this->medicalRecordService->store($request, $idPatient);
            $name = $this->patientService->find($idPatient)->name;
            return redirect()->route('patients.index')->with('message-success', 'Thêm mới Bệnh án cho '.$name.' thành công!');
        } catch (\Exception $e) {
            return redirect()->route('patients.index')->with('message-failed', 'Thêm mới Bệnh án thất bại!');
        }
    }

    public function show($idPatient)
    {
        $patient = $this->patientService->find($idPatient);
        return view('medical-records.show', compact('patient'));
    }

    public function edit($idPatient, $idMedicalRecord)
    {
        $medicalRecord = $this->medicalRecordService->find($idMedicalRecord);
        $patient = $this->patientService->find($idPatient);
        return view('medical-records.edit', compact('medicalRecord', 'patient'));
    }

    public function update($idPatient, $idMedicalRecord, MedicalRecordUpdateRequest $request)
    {
        try {
            $this->medicalRecordService->update($request, $idMedicalRecord);
            return redirect()->route('patients.medical-record.show',
                ['id' => $idPatient, 'idMedical' => $idMedicalRecord])->with('message-success',
                'Chỉnh sửa Bệnh án thành công!');
        } catch (\Exception $e) {
            return redirect()->route('patients.medical-record.show',
                ['id' => $idPatient, 'idMedical' => $idMedicalRecord])->with('message-failed',
                'Chỉnh sửa Bệnh án thất bại!');
        }
    }
}

resources/views/medical-records/create.blade.php
@extends('layouts.app', ['title' => 'Thêm bệnh án'])
@push('css')
    <link rel="stylesheet" href="{{ asset('css/medical-record.css') }}">
@endpush
@section('content')
    <div class="info-private">
        <h3 class="text-center mb-4">Thông tin cá nhân</h3>
        <div class="row">
            <div class="col-3">
                <div class="avatar-patient">
                    <img src="{{ asset('images/uploads/'. $patient->avatar) }}" alt="avatar">
                </div>
            </div>
            <div class="col-9">
                <div class="row">
                    <div class="form-group col-6">
                        <label for="name">Họ và tên</label>
                        <input type="text" class="form-control" placeholder="Họ và tên..."
                               value="{{ $patient->name }}" disabled>
                    </div>
                    <div class="form-group col-6">
                        <label for="name">Giới tính</label>
                        <input type="text" class="form-control" placeholder="Họ và tên..."
                               value="{{ config('constants.gender')[$patient->gender] }}" disabled>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Ngày sinh</label>
                            <input type="text" class="form-control" placeholder="dd-mm-yy"
                                   value="{{ $patient->date_of_birth->format('d/m/Y') }}" disabled>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Số điện thoại</label>
                            <input type="text" class="form-control" placeholder="dd-mm-yy"
                                   value="{{ $patient->phone }}" disabled>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label for="name">Địa chỉ</label>
                            <input type="text" class="form-control" placeholder="dd-mm-yy"
                                   value="{{ $patient->city.', '.$patient->district.', '.$patient->commune.', '.$patient->apartment_number }}"
                                   disabled>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="line"></div>
    <div class="medical-record">
        <h3 class="text-center">Bệnh án</h3>
        <form method="POST" action="{{ route('patients.medical-record.store', $patient->id) }}">
            @csrf
            <div class="row">
                <div class="form-group col-4">
                    <label for="check-in">Thời gian tiếp nhận</label>
                    <input type="datetime-local" class="form-control" id="check-in" name="check_in"
                           value="{{request()->old('check_out')=== null ? '' :old('check_in', request()->check_in) }}">
                    @error('check_in')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group col-4">
                    <label for="check-out">Thời gian ra viện</label>
                    <input type="datetime-local" class="form-control"  id="check-out" name="check_out"
                           value="{{ old('check_out', request()->check_out) }}"
                           @if(!request()->old('check_out')) disabled @endif>
                    @error('check_out')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                    <div id="error-check-out"></div>
                </div>
                <div class="form-group col-4">
                    <label for="check-in">Nơi tiếp nhận</label>
                    <select name="where_check_in" class="form-control">
                        <option value="" disabled selected>---Chọn---</option>
                        @foreach(config('constants.department') as $key => $value)
                            <option value="{{ $key }}" @if(request()->old('where_check_in') == $key) selected @endif>{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('where_check_in')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="row">
                <div class="form-group col-4">
                    <label for="total-day">Tổng số ngày</label>
                    <input type="text" class="form-control" id="total-day" name="total_day" placeholder="Nhập..." value="{{ old('total_day', request()->total_day) }}">
                    @error('total_day')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group col-4">
                    <label for="diagnose">Chẩn đoán</label>
                    <input type="text" class="form-control" id="diagnose" name="diagnose" placeholder="Nhập..." value="{{ old('diagnose', request()->diagnose) }}">
                    @error('diagnose')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group col-4">
                    <label for="pathology">Giải phẫu bệnh</label>
                    <select name="pathology" class="form-control">
                        <option value="" disabled selected>---Chọn---</option>
                        @foreach(config('constants.pathology') as $key => $value)
                            <option value="{{ $key }}" @if(request()->old('pathology') == $key) selected @endif>{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('pathology')
                    <small class="form-text text-danger">{{$message}}</small>
                    @enderror
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label for="autopsy">Khám nghiệm tử thi</label>
                        <select name="autopsy" class="form-control" id="autopsy">
                            <option value="" disabled selected>---Chọn---</option>
                            @foreach(config('constants.confirm') as $key => $value)
                                <option value="{{ $key }}" @if(request()->old('autopsy') == $key) selected @endif>{{ $value }}</option>
                            @endforeach
                        </select>
                        @error('autopsy')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row" id="autopsy-child">
                @if(request()->old('autopsy') == 1)
                    <div class="form-group col-6">
                        <label for="time-to-corpse" class="smal-label">Thời gian nhận tử thi</label>
                        <input type="datetime-local" class="form-control" id="time-to-corpse" name="time_to_corpse"
                               value="{{ old('time_to_corpse', request()->time_to_corpse) }}">
                        @error('time_to_corpse')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group col-6">
                        <label for="time-to-examination" class="smal-label">Thời gian khám nghiệm</label>
                        <input type="datetime-local" class="form-control" id="time-to-examination"
                               name="time_to_examination"
                               value="{{ old('time_to_examination', request()->time_to_examination) }}">
                        @error('time_to_examination')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>
                @endif
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label for="result">kết quả</label>
                        <select name="result" class="form-control" id="result">
                            <option value="" disabled selected>---Chọn---</option>
                            @foreach(config('constants.result') as $key => $value)
                                <option value="{{ $key }}" @if(request()->old('result') == $key) selected @endif>{{ $value }}</option>
                            @endforeach
                        </select>
                        @error('result')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row" id="result-child">
                @if(request()->old('result') == 5)
                    <div class="form-group col-6">
                        <label for="time-die" class="smal-label">Thời gian tử vong</label>
                        <input type="datetime-local" class="form-control" id="time-die" name="time_die"
                               value="{{ old('time_die', request()->time_die) }}">
                        @error('time_die')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group col-6">
                        <label for="reason-die" class="smal-label">Lý do</label>
                        <input type="text" class="form-control" id="reason-die" name="reason_die"
                               value="{{ old('reason_die', request()->reason_die) }}">
                        @error('reason_die')
                        <small class="form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>
                @endif
            </div>
            <div class="group-btn text-center mt-4">
                <a href="{{ route('patients.index') }}" class="btn btn-danger">
                    Quay lại
                </a>
                <button class="btn btn-primary" type="submit">Thêm</button>
            </div>
        </form>
    </div>
    <div style="height: 200px"></div>
@endsection

@push('js')
    <script src="{{asset('js/medical-record.js')}}" type="module"></script>
@endpush

resources/views/medical-records/show.blade.php
@extends('layouts.app', ['title' => 'Thêm bệnh án'])
@push('css')
    <link rel="stylesheet" href="{{ asset('css/medical-record.css') }}">
@endpush
@section('content')
    <div class="info-private">
        <div class="position-relative">
            <div class="position-absolute">
                <a href="{{ route('patients.index') }}" class="btn btn-sm btn-danger">
                    Quay lại
                </a>
            </div>
            <h3 class="mb-4 text-center">Thông tin cá nhân</h3>
        </div>
        <div class="row">
            <div class="col-3">
                <div class="avatar-patient">
                    <img src="{{ asset('images/uploads/'. $patient->avatar) }}" alt="avatar">
                </div>
            </div>
            <div class="col-9">
                <div class="row">
                    <div class="form-group col-6">
                        <label for="name">Họ và tên</label>
                        <input type="text" class="form-control" placeholder="Họ và tên..."
                               value="{{ $patient->name }}" disabled>
                    </div>
                    <div class="form-group col-6">
                        <label for="name">Giới tính</label>
                        <input type="text" class="form-control" placeholder="Họ và tên..."
                               value="{{ config('constants.gender')[$patient->gender] }}" disabled>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Ngày sinh</label>
                            <input type="text" class="form-control" placeholder="dd-mm-yy"
                                   value="{{ $patient->date_of_birth->format('d/m/Y') }}" disabled>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Số điện thoại</label>
                            <input type="text" class="form-control" placeholder="dd-mm-yy"
                                   value="{{ $patient->phone }}" disabled>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label for="name">Địa chỉ</label>
                            <input type="text" class="form-control" placeholder="dd-mm-yy"
                                   value="{{ $patient->city.', '.$patient->district.', '.$patient->commune.', '.$patient->apartment_number }}"
                                   disabled>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="line"></div>
    <div class="medical-record">
        @include('messages.message')
        <h3 class="text-center">Bệnh án</h3>
        @php
            $department = config('constants.department');
            $pathology = config('constants.pathology');
            $confirm = config('constants.confirm');
            $result = config('constants.result')
        @endphp
        @if(count($patient->medicalRecords) > 0)
            @foreach($patient->medicalRecords as $medicalRecord)
                <div class="wrapper-medical-record">
                    <div class="d-flex align-items-center mb-3">
                        <h4 class="text-uppercase m-0 mr-4 text-info">Mã bệnh án: {{ $medicalRecord->medical_record_code  }}</h4>
                        <a href="{{ route('patients.medical-record.edit', ['id' => $patient->id, 'idMedical' => $medicalRecord->id]) }}" style="text-decoration: underline"><i class="fas fa-pen"></i>Chỉnh sửa...</a>
                    </div>
                    <div class="row">
                        <div class="form-group col-4">
                            <label for="check-in">Thời gian tiếp nhận</label>
                            <div class="d-flex">
                                <div class="mr-4">Ngày: {{ $medicalRecord->check_in->format('d/m/Y ') }}</div>
                                <div>Giờ: {{ $medicalRecord->check_in->format('H:i:s') }}</div>
                            </div>
                        </div>
                        <div class="form-group col-4">
                            <label for="check-out">Thời gian ra viện</label>
                            <div class="d-flex">
                                <div class="mr-4">Ngày: {{ $medicalRecord->check_out->format('d/m/Y ') }}</div>
                                <div>Giờ: {{ $medicalRecord->check_out->format('H:i:s') }}</div>
                            </div>
                        </div>
                        <div class="form-group col-4">
                            <label for="check-in">Nơi tiếp nhận</label>
                            <div>{{ $department[$medicalRecord->where_check_in] }}</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-4">
                            <label for="total-day">Tổng số ngày</label>
                            <div>{{ $medicalRecord->total_day }} ngày</div>
                        </div>
                        <div class="form-group col-4">
                            <label for="diagnose">Chẩn đoán</label>
                            <div>{{ $medicalRecord->diagnose }}</div>
                        </div>
                        <div class="form-group col-4">
                            <label for="pathology">Giải phẫu bệnh</label>
                            <div>{{ $pathology[$medicalRecord->pathology] }}</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <label for="autopsy">Khám nghiệm tử thi</label>
                                <div>{{ $confirm[$medicalRecord->autopsy] }}</div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="autopsy">Thời gian nhận tử thi</label>
                                @if($medicalRecord->autopsy == 1)
                                    <div class="d-flex">
                                        <div class="mr-4">Ngày: {{ $medicalRecord->time_to_corpse->format('d/m/Y ') }}</div>
                                        <div>Giờ: {{ $medicalRecord->time_to_corpse->format('H:i:s') }}</div>
                                    </div>
                                @else
                                    <div class="text-danger">N/a</div>
                                @endif
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="autopsy">Thời gian khám nghiệm</label>
                                @if($medicalRecord->autopsy == 1)
                                    <div class="d-flex">
                                        <div class="mr-4">Ngày: {{ $medicalRecord->time_to_examination->format('d/m/Y ') }}</div>
                                        <div>Giờ: {{ $medicalRecord->time_to_examination->format('H:i:s') }}</div>
                                    </div>
                                @else
                                    <div class="text-danger">N/a</div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <label for="result">kết quả</label>
                                <div>{{ $result[$medicalRecord->result] }}</div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="autopsy">Thời gian tử vong</label>
                                @if($medicalRecord->result == 5)
                                    <div class="d-flex">
                                        <div class="mr-4">Ngày: {{ $medicalRecord->time_die->format('d/m/Y ') }}</div>
                                        <div>Giờ: {{ $medicalRecord->time_die->format('H:i:s') }}</div>
                                    </div>
                                @else
                                    <div class="text-danger">N/a</div>
                                @endif
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="autopsy">Lý do</label>
                                @if($medicalRecord->result == 5)
                                    <div>{{ $medicalRecord->reason_die }}</div>
                                @else
                                    <div class="text-danger">N/a</div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="col-4">
                            <div class="text-center">
                                <label class="text-uppercase">người lập bệnh án</label>
                                <div>Bs</div>
                                <div class="font-italic text-uppercase">{{ $medicalRecord->name_doctor }}</div>
                            </div>
                        </div>
                    </div>
                    @if($loop->iteration !== count($patient->medicalRecords))
                        <div class="line-medical"></div>
                    @endif
                </div>
            @endforeach
        @else
            <div class="row">
                <div class="col-12">
                    <p class="text-danger text-center">Không tìm tìm thấy dữ liệu!</p>
                </div>
            </div>
        @endif
    </div>
    <div style="height: 200px"></div>
@endsection

@push('js')
    <script src="{{asset('js/medical-record.js')}}" type="module"></script>
@endpush